server:
  ssl:
    enabled: true
    client-auth: want
  port: 8443

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, flyway, info

twba:
  application:
    name: "course-management"
    uri: "https://thewhiteboardarchitect.com/${twba.application.name}"
  allowed-services:
    -
      service-name: rating-service
      roles:
        - READ
        - WRITE
    -
      service-name: fake-service
      roles:
        - READ

spring:
  application:
    name: "course-management-service"
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 8
      pool-name: "cdc-pool"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    schemas: db_migrations
    out-of-order: true
    enabled: true
logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

outbox:
  num-partitions: 1