server:
  port: 9096

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, flyway, info

twba:
  application:
    name: "rating-system"
    uri: "https://thewhiteboardarchitect.com/${twba.application.name}"


spring:
  application:
    name: "rating-system-service"
  rabbitmq:
    host: ${RATING_SYSTEM_RABBITMQ_HOST}
    port: ${RATING_SYSTEM_RABBITMQ_PORT}
    username: ${RATING_SYSTEM_RABBITMQ_USERNAME}
    password: ${RATING_SYSTEM_RABBITMQ_PASSWORD}