server:
  port: 9096

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, flyway, info

twba:
  application:
    name: "rating-system"
    uri: "https://thewhiteboardarchitect.com/${twba.application.name}"
  mtls-client:
    key-store-path: ${KEYSTORE_FOLDER}/keystore-rating-system.jks
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: rating-system
    key-password: ${PRIVATE_KEY_PASSWORD}
    trust-store-path: ${TRUSTSTORE_FOLDER}/truststore.jks
    trust-store-password: ${TRUST_STORE_PASSWORD}
  external-services:
    - service-name: "course-management"
      service-url: ${COURSE_MANAGEMENT_URL:http://localhost:9095}


spring:
  application:
    name: "rating-system-service"
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://${POSTGRES_SERVICE_NAME}:${POSTGRES_SERVICE_PORT}/${POSTGRES_DB_NAME}"
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 8
      pool-name: "rating-system-pool"
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    schemas: db_migrations
    out-of-order: true
    enabled: true