server:
  ssl:
    key-store: ${KEYSTORE_FOLDER}/keystore-rating-system.jks
    key-store-password: ${CERTS_PASSWORD}
    key-alias: rating-system
    key-password: ${CERTS_PASSWORD}
    trust-store: ${TRUSTSTORE_FOLDER}/truststore.jks
    enabled: true
    trust-store-password: ${CERTS_PASSWORD}
    client-auth: need
  port: 8444

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, flyway, info

twba:
  application:
    name: "rating-system"
    uri: "https://thewhiteboardarchitect.com/${twba.application.name}"
  mtls-client:
    key-store-path: ${KEYSTORE_FOLDER}/keystore-rating-system.jks
    key-store-password: ${CERTS_PASSWORD}
    key-alias: rating-system
    key-password: ${CERTS_PASSWORD}
    trust-store-path: ${TRUSTSTORE_FOLDER}/truststore.jks
    trust-store-password: ${CERTS_PASSWORD}


spring:
  application:
    name: "rating-system-service"
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}